package com.example.apiscanner.service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import org.springframework.stereotype.Service;
import com.example.apiscanner.model.ScanResult;
import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;

@Service
public class PdfService {

	public byte[] generatePdf(ScanResult result) {

		try {

			Document document = new Document(PageSize.A4, 40, 40, 50, 50);

			ByteArrayOutputStream out = new ByteArrayOutputStream();

			PdfWriter.getInstance(document, out);

			document.open();

			// ==========================
			// HEADER
			// ==========================

			Font titleFont = new Font(Font.HELVETICA, 22, Font.BOLD, Color.BLUE);

			Paragraph title = new Paragraph("CyberRadar Security Report", titleFont);

			title.setAlignment(Element.ALIGN_CENTER);

			document.add(title);

			document.add(new Paragraph(" "));

			document.add(new Paragraph("Generated On : "
					+ LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss"))));

			document.add(new Paragraph(" "));

			// ==========================
			// SECURITY SCORE
			// ==========================

			int score = calculateScore(result);

			String riskLevel = score >= 80 ? "LOW" : score >= 50 ? "MEDIUM" : "HIGH";

			document.add(new Paragraph("Target URL : " + result.getUrl()));

			document.add(new Paragraph("Security Score : " + score + "/100"));

			document.add(new Paragraph("Risk Level : " + riskLevel));

			document.add(new Paragraph(" "));

			// ==========================
			// RESULTS TABLE
			// ==========================

			PdfPTable table = new PdfPTable(2);

			table.setWidthPercentage(100);

			table.addCell("Security Check");
			table.addCell("Status");

			table.addCell("HTTPS");
			table.addCell(result.getHttps());

			table.addCell("X-Frame-Options");
			table.addCell(result.getxFrameOptions());

			table.addCell("Content-Security-Policy");
			table.addCell(result.getContentSecurityPolicy());

			table.addCell("HSTS");
			table.addCell(result.getStrictTransportSecurity());

			table.addCell("X-Content-Type-Options");
			table.addCell(result.getxContentTypeOptions());

			document.add(table);

			document.add(new Paragraph(" "));

			// ==========================
			// RECOMMENDATIONS
			// ==========================

			Font heading = new Font(Font.HELVETICA, 14, Font.BOLD);

			document.add(new Paragraph("Recommendations", heading));

			document.add(new Paragraph(" "));

			if ("Missing".equalsIgnoreCase(result.getxFrameOptions())) {

				document.add(new Paragraph("• Enable X-Frame-Options Header"));
			}

			if ("Missing".equalsIgnoreCase(result.getContentSecurityPolicy())) {

				document.add(new Paragraph("• Configure Content Security Policy"));
			}

			if ("Missing".equalsIgnoreCase(result.getStrictTransportSecurity())) {

				document.add(new Paragraph("• Enable HSTS Header"));
			}

			document.add(new Paragraph(" "));

			// ==========================
			// FOOTER
			// ==========================

			Paragraph footer = new Paragraph("Generated by CyberRadar | Scan • Detect • Secure");

			footer.setAlignment(Element.ALIGN_CENTER);

			document.add(footer);

			document.close();

			return out.toByteArray();

		} catch (Exception e) {

			throw new RuntimeException(e);
		}
	}

	private int calculateScore(ScanResult result) {

		int score = 0;

		if ("Enabled".equalsIgnoreCase(result.getHttps()))
			score += 20;

		if (!"Missing".equalsIgnoreCase(result.getxFrameOptions()))
			score += 20;

		if (!"Missing".equalsIgnoreCase(result.getContentSecurityPolicy()))
			score += 20;

		if (!"Missing".equalsIgnoreCase(result.getStrictTransportSecurity()))
			score += 20;

		if (!"Missing".equalsIgnoreCase(result.getxContentTypeOptions()))
			score += 20;

		return score;
	}

}
