package com.example.apiscanner.service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import org.springframework.stereotype.Service;
import com.example.apiscanner.model.APIScanResult;
import com.example.apiscanner.model.JwtScanResult;
import com.example.apiscanner.model.OwaspScanResult;
import com.example.apiscanner.model.SwaggerScanResult;
import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import com.lowagie.text.Phrase;
import com.lowagie.text.Rectangle;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.*;

@Service
public class PdfService {

	// ==========================================================
	// COMMON DATE FORMATTER
	// Used in all reports
	// Format : dd-MM-yyyy HH:mm:ss
	// Example : 10-06-2026 16:45:20
	// ==========================================================

	public String getFormattedDateTime() {

		DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");

		return LocalDateTime.now().format(formatter);
	}

	// ==========================================================
	// COMMON HEADER
	// Adds blue CyberRadar banner
	// Adds report title
	// Reused by all PDF reports
	// ==========================================================

	private void addHeader(Document document, String reportName) throws Exception {

		Font titleFont = new Font(Font.HELVETICA, 24, Font.BOLD, Color.WHITE);

		PdfPTable headerTable = new PdfPTable(1);

		headerTable.setWidthPercentage(100);

		PdfPCell cell = new PdfPCell(new Phrase("CyberRadar Security Report", titleFont));

		cell.setBackgroundColor(new Color(25, 118, 210));

		cell.setHorizontalAlignment(Element.ALIGN_CENTER);

		cell.setPadding(15);

		cell.setBorder(Rectangle.NO_BORDER);

		headerTable.addCell(cell);

		document.add(headerTable);

		document.add(new Paragraph(" "));

		Font reportFont = new Font(Font.HELVETICA, 18, Font.BOLD, Color.DARK_GRAY);

		Paragraph reportTitle = new Paragraph(reportName, reportFont);

		reportTitle.setAlignment(Element.ALIGN_CENTER);

		document.add(reportTitle);

		document.add(new Paragraph(" "));
	}

	// ==========================================================
	// COMMON FOOTER
	// Appears at end of every report
	// ==========================================================

	public class FooterPageEvent extends PdfPageEventHelper {

		@Override
		public void onEndPage(PdfWriter writer, Document document) {

			Font footerFont = new Font(Font.HELVETICA, 9, Font.ITALIC, Color.GRAY);

			Phrase footer = new Phrase("Generated by CyberRadar | Scan • Detect • Secure", footerFont);

			ColumnText.showTextAligned(writer.getDirectContent(), Element.ALIGN_CENTER, footer,
					document.getPageSize().getWidth() / 2, 30, 0);
		}
	}

	// ==========================================================
	// TABLE HEADER CELL
	// Blue background
	// White bold text
	// ==========================================================

	private PdfPCell getHeaderCell(String text) {

		Font font = new Font(Font.HELVETICA, 12, Font.BOLD, Color.WHITE);

		PdfPCell cell = new PdfPCell(new Phrase(text, font));

		cell.setBackgroundColor(new Color(33, 150, 243));

		cell.setPadding(8);

		return cell;
	}

	// ==========================================================
	// NORMAL TABLE CELL
	// Used for labels and values
	// ==========================================================

	private PdfPCell getDataCell(String text) {

		Font font = new Font(Font.HELVETICA, 11);

		PdfPCell cell = new PdfPCell(new Phrase(text, font));

		cell.setPadding(6);

		return cell;
	}

	// ==========================================================
	// STATUS CELL
	//
	// GREEN :
	// Enabled / Present / Low Risk
	//
	// RED :
	// Missing / Not Enabled / High Risk
	// ==========================================================

	private PdfPCell getStatusCell(String status) {

		Font font = new Font(Font.HELVETICA, 11, Font.BOLD);

		PdfPCell cell = new PdfPCell(new Phrase(status, font));

		if (status != null && (status.contains("Enabled") || status.contains("Present") || status.contains("Low"))) {

			cell.setBackgroundColor(new Color(200, 255, 200));
		} else {

			cell.setBackgroundColor(new Color(255, 220, 220));
		}

		cell.setPadding(6);

		return cell;
	}

	// ====================================================
	// HEADER SCANNER PDF
	// ====================================================

	// ==========================================================
	// HEADER SECURITY REPORT PDF
	//
	// Purpose:
	// Generates report for security headers
	//
	// Checks:
	// HTTPS
	// HSTS
	// CSP
	// X-Frame-Options
	// X-Content-Type
	// ==========================================================
	public byte[] generateHeaderPdf(APIScanResult result) {

		try {

			Document document = new Document(PageSize.A4);

			ByteArrayOutputStream out = new ByteArrayOutputStream();

			PdfWriter writer = PdfWriter.getInstance(document, out);

			writer.setPageEvent(new FooterPageEvent());

			document.open();

			addHeader(document, "Header Security Report");

			Font infoFont = new Font(Font.HELVETICA, 11);

			document.add(new Paragraph("Target URL : " + result.getUrl(), infoFont));

			document.add(new Paragraph("Generated On : " + getFormattedDateTime(), infoFont));

			document.add(new Paragraph(" "));

			PdfPTable table = new PdfPTable(2);

			table.setWidthPercentage(100);

			table.addCell(getHeaderCell("Security Header"));
			table.addCell(getHeaderCell("Status"));

			table.addCell(getDataCell("HTTPS"));
			table.addCell(getStatusCell(result.getHttps()));

			table.addCell(getDataCell("X-Frame-Options"));
			table.addCell(getStatusCell(result.getxFrameOptions()));

			table.addCell(getDataCell("CSP"));
			table.addCell(getStatusCell(result.getContentSecurityPolicy()));

			table.addCell(getDataCell("HSTS"));
			table.addCell(getStatusCell(result.getStrictTransportSecurity()));

			table.addCell(getDataCell("X-Content-Type"));
			table.addCell(getStatusCell(result.getxContentTypeOptions()));

			table.addCell(getDataCell("X-XSS-Protection"));
			table.addCell(getStatusCell(result.getxXssProtection()));

			table.addCell(getDataCell("Referrer Policy"));
			table.addCell(getStatusCell(result.getReferrerPolicy()));

			table.addCell(getDataCell("Permissions Policy"));
			table.addCell(getStatusCell(result.getPermissionsPolicy()));

			table.addCell(getDataCell("Access-Control-Allow-Origin"));
			table.addCell(getStatusCell(result.getAccessControlAllowOrigin()));

			table.addCell(getDataCell("Cache-Control"));
			table.addCell(getStatusCell(result.getCacheControl()));

			table.addCell(getDataCell("Server"));
			table.addCell(getStatusCell(result.getServer()));

			document.add(table);

			document.close();

			return out.toByteArray();

		} catch (Exception e) {

			throw new RuntimeException("Error generating Header PDF", e);
		}
	}

	// ====================================================
	// SWAGGER PDF
	// ====================================================

	public byte[] generateSwaggerPdf(SwaggerScanResult result) {

		try {

			Document document = new Document(PageSize.A4);

			ByteArrayOutputStream out = new ByteArrayOutputStream();

			PdfWriter writer = PdfWriter.getInstance(document, out);

			writer.setPageEvent(new FooterPageEvent());

			document.open();

			addHeader(document, "Swagger Security Report");

			Font infoFont = new Font(Font.HELVETICA, 11);

			document.add(new Paragraph("Swagger URL : " + result.getSwaggerUrl(), infoFont));

			document.add(new Paragraph("Generated On : " + getFormattedDateTime(), infoFont));

			document.add(new Paragraph(" "));

			PdfPTable table = new PdfPTable(2);

			table.setWidthPercentage(100);

			table.addCell(getHeaderCell("Security Check"));
			table.addCell(getHeaderCell("Status"));

			table.addCell(getDataCell("HTTPS"));
			table.addCell(getStatusCell(result.getHttps()));

			table.addCell(getDataCell("Bearer Authentication"));
			table.addCell(getStatusCell(result.getBearerAuth()));

			table.addCell(getDataCell("Global Security"));
			table.addCell(getStatusCell(result.getGlobalSecurity()));

			table.addCell(getDataCell("Total APIs"));
			table.addCell(getDataCell(String.valueOf(result.getTotalApis())));

			document.add(table);

			document.close();

			return out.toByteArray();

		} catch (Exception e) {

			throw new RuntimeException(e);
		}
	}

	// ====================================================
	// JWT PDF
	// ====================================================

	public byte[] generateJwtPdf(JwtScanResult result) {

		try {

			Document document = new Document(PageSize.A4);

			ByteArrayOutputStream out = new ByteArrayOutputStream();

			PdfWriter writer = PdfWriter.getInstance(document, out);

			writer.setPageEvent(new FooterPageEvent());

			document.open();

			addHeader(document, "JWT Analysis Report");

			Font infoFont = new Font(Font.HELVETICA, 11);

			document.add(new Paragraph("Generated On: " + getFormattedDateTime(), infoFont));

			document.add(new Paragraph(" "));

			PdfPTable table = new PdfPTable(2);
			table.setWidthPercentage(100);

			table.addCell(getHeaderCell("JWT Property"));
			table.addCell(getHeaderCell("Value"));

			table.addCell(getDataCell("Algorithm"));
			table.addCell(getDataCell(result.getAlgorithm()));

			table.addCell(getDataCell("Issuer"));
			table.addCell(getDataCell(result.getIssuer()));

			table.addCell(getDataCell("Audience"));
			table.addCell(getDataCell(result.getAudience()));

			table.addCell(getDataCell("Expiration"));
			table.addCell(getDataCell(result.getExpiration()));

			table.addCell(getDataCell("Risk Score"));
			table.addCell(getDataCell(String.valueOf(result.getRiskScore())));

			table.addCell(getDataCell("Token Type"));
			table.addCell(getDataCell(result.getTokenType()));

			document.add(table);

			document.close();

			return out.toByteArray();

		} catch (Exception e) {

			throw new RuntimeException(e);
		}
	}

	// ====================================================
	// OWASP PDF
	// ====================================================

	public byte[] generateOwaspPdf(OwaspScanResult result) {

		try {

			Document document = new Document(PageSize.A4);

			ByteArrayOutputStream out = new ByteArrayOutputStream();

			PdfWriter writer = PdfWriter.getInstance(document, out);

			writer.setPageEvent(new FooterPageEvent());

			document.open();

			addHeader(document, "OWASP Top 10 Report");

			Font infoFont = new Font(Font.HELVETICA, 11);

			document.add(new Paragraph("Generated On : " + getFormattedDateTime(), infoFont));

			document.add(new Paragraph(" "));

			PdfPTable table = new PdfPTable(2);

			table.setWidthPercentage(100);

			table.addCell(getHeaderCell("OWASP Check"));
			table.addCell(getHeaderCell("Result"));

			table.addCell(getDataCell("Broken Access Control"));
			table.addCell(getStatusCell(result.getBrokenAccessControl()));

			table.addCell(getDataCell("Cryptographic Failures"));
			table.addCell(getStatusCell(result.getCryptographicFailures()));

			table.addCell(getDataCell("Injection"));
			table.addCell(getStatusCell(result.getInjectionRisk()));

			table.addCell(getDataCell("Security Misconfiguration"));
			table.addCell(getStatusCell(result.getSecurityMisconfiguration()));

			table.addCell(getDataCell("Insecure Design"));
			table.addCell(getStatusCell(result.getInsecureDesign()));

			table.addCell(getDataCell("Vulnerable Components"));
			table.addCell(getStatusCell(result.getVulnerableComponents()));

			table.addCell(getDataCell("Identification Failures"));
			table.addCell(getStatusCell(result.getIdentificationFailures()));

			table.addCell(getDataCell("Software Integrity Failures"));
			table.addCell(getStatusCell(result.getSoftwareIntegrityFailures()));

			table.addCell(getDataCell("Logging Failures"));
			table.addCell(getStatusCell(result.getLoggingFailures()));

			table.addCell(getDataCell("SSRF Risk"));
			table.addCell(getStatusCell(result.getSsrfRisk()));

			table.addCell(getDataCell("Overall Risk"));
			table.addCell(getStatusCell(result.getOverallRisk()));

			table.addCell(getDataCell("Risk Score"));
			table.addCell(getDataCell(result.getRiskScore() + "/100"));

			document.add(table);

			document.close();

			return out.toByteArray();

		} catch (Exception e) {

			throw new RuntimeException(e);
		}
	}

}
